### ISSUE TITLE
Server crashes after displaying "Game detected: csgo" on the console

### ISSUE THREAD

**Issue by qq410525209** [oylsister/ZLeader-Remake#11]
After loading the plugin, Server crashes after displaying "Game detected: csgo" on the console
After restarting the server program, the situation remains the same
`L 02/09/2024 - 08:34:42: [basecommands.smx] "Admins<2>" console command (cmdline "sm plugins load leader_ultimate.smx")
Game detected: csgo
`
sourcemod-1.10.0

**Comment by oylsister** [comment]
> After loading the plugin, Server crashes after displaying "Game detected: csgo" on the console After restarting the server program, the situation remains the same `L 02/09/2024 - 08:34:42: [basecommands.smx] "Admins<2>" console command (cmdline "sm plugins load leader_ultimate.smx") Game detected: csgo ` sourcemod-1.10.0

Unfortunately, I'm no longer working on this project, since the coming cs2 and CS:S community has taken over this project.
